version: "3.9"

services:
  godot_private_asset_library:
    container_name: godot_private_asset_library
    build:
      context: .
      dockerfile: container/Dockerfile
    volumes:
      - ./godot_assets:/app/godot_assets
      - ./cache/:/app/cache
    ports:
      - "8080:8080"
